name: Test action-clang-tidy workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        reporter: [ github-check, github-pr-review, github-pr-annotations ]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: CMake
        env:
          CC: clang
        working-directory: test
        run: cmake -B ./build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: ./
        with:
          workdir: ./test/build
          reporter: ${{ matrix.reporter }}
          fail_on_error: false
