name: Test action-clang-tidy workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        reporter: [ github-check, github-pr-review, github-pr-annotations ]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.3.1

      - name: CMake
        env:
          CC: clang
        working-directory: test
        run: cmake -B ./build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: ./
        with:
          workdir: ./test/build
          reporter: ${{ matrix.reporter }}
          fail_on_error: false
